#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_DIR="${ROOT_DIR}/native-ios/Config"
OUTPUT_FILE="${OUTPUT_DIR}/NativeLocal.xcconfig"

read_env_value() {
  local key="$1"
  local file

  for file in "${ROOT_DIR}/.env" "${ROOT_DIR}/.env.submit"; do
    [[ -f "${file}" ]] || continue

    local line
    line="$(grep -E "^${key}=" "${file}" | tail -n 1 || true)"
    [[ -n "${line}" ]] || continue

    local value="${line#*=}"
    value="${value%$'\r'}"
    value="${value%\"}"
    value="${value#\"}"
    value="${value%\'}"
    value="${value#\'}"
    printf '%s' "${value}"
    return 0
  done

  return 1
}

escape_xcconfig_value() {
  local value="$1"
  local escaped_comment_slash='/$()/'
  # xcconfig treats // as a comment, so keep URL values intact through expansion.
  value="${value//\/\//$escaped_comment_slash}"
  printf '%s' "${value}"
}

mkdir -p "${OUTPUT_DIR}"

SUPABASE_URL_VALUE="$(read_env_value EXPO_PUBLIC_SUPABASE_URL || true)"
SUPABASE_KEY_VALUE="$(read_env_value EXPO_PUBLIC_SUPABASE_KEY || true)"

{
  printf '// Generated by scripts/generate-native-ios-config.sh. Do not commit.\n'
  printf 'SUPABASE_URL = %s\n' "$(escape_xcconfig_value "${SUPABASE_URL_VALUE}")"
  printf 'SUPABASE_ANON_KEY = %s\n' "$(escape_xcconfig_value "${SUPABASE_KEY_VALUE}")"
  printf 'INFOPLIST_KEY_SUPABASE_URL = $(SUPABASE_URL)\n'
  printf 'INFOPLIST_KEY_SUPABASE_ANON_KEY = $(SUPABASE_ANON_KEY)\n'
} > "${OUTPUT_FILE}"

if [[ -z "${SUPABASE_URL_VALUE}" || -z "${SUPABASE_KEY_VALUE}" ]]; then
  echo "Native iOS config generated without Supabase credentials; app will use sample mode."
else
  echo "Native iOS config generated with Supabase credentials."
fi
